create table if not exists client
(
    id int8 generated by default as identity,
    email varchar(255) not null,
    name varchar(255) not null,
    birth_date timestamp,
    primary key (id)
    );

create table if not exists product
(
    id int8 generated by default as identity,
    description varchar(255),
    name varchar(255) not null,
    price float8 not null,
    primary key (id)
    );

create table if not exists sale
(
    id int8 generated by default as identity,
    products jsonb,
    client_id int8 not null,
    primary key (id)
    );

alter table if exists sale add constraint FKon0o9ba5ajsnwivekhl1tfjiy foreign key (client_id) references client;